config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index' 

  get 'mailer/compose' => 'mailer#compose', as: :mailer_compose
  get 'mailer/inbox' => 'mailer#inbox', as: :mailer_inbox
  get 'mailer/sent_mails' => 'mailer#sent_mails', as: :sent_mails
  get 'mailer/history/:ticket_id' => 'mailer#history', as: :history
  post 'mailer/create_mail/:ticket_id' => 'mailer#create_mail', as: :create_mail

  get 'about' => 'staticpages#about', as: :about
  get 'contact' => 'staticpages#contact', as: :contact
  get 'homepage' => 'home#index', as: :homepage

  get 'problem/add' => 'problem#add', as: :problem_add
  get 'problem/all' => 'problem#all', as: :problem_all
  get 'problem/create' => 'problem#create_problem', as: :create_problem
  get 'problem/view/:id' => 'problem#view', as: :problem_view
  get 'user/all_problems' => 'problem#user_problems',as: :user_all_problems
  get 'user/edit/:id' => 'problem#edit',as: :user_edit
  get 'user/edit_problem/:id' => 'problem#edit_problem', as: :user_edit_problem
  get 'problem/add_comment/:id' => 'problem#add_comment', as: :problem_add_comment

  get 'group/index' => 'group#index',as: :group_index
  get 'group/create' => 'group#create',as: :group_create
  get 'group/groups' => 'group#groups',as: :group_groups
  get 'group/info/:id' => 'group#info', as: :group_info
  get 'group/other/groups' => 'group#other',as: :group_other

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :problem
	belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user
	has_many :group_users
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
	has_many :comments
	has_many :submissions
	belongs_to :user
end

app/models/submission.rb
class Submission < ActiveRecord::Base
	belongs_to :user
	belongs_to :problem
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  	has_many :submissions
	has_many :comments
	has_many :problems
	has_many :groups
	has_many :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
	def index
	end
	def create
		group = Group.new
		group.name = params[:name]
		group.no_of_members = params[:no_of_members].to_i
		group.user_id = current_user.id
		group.save!
		i=2
		group_usr = GroupUser.new
		group_usr.group_id = group.id
		group_usr.user_id = current_user.id
		group_usr.save!
		while i<=group.no_of_members do
			d = "user_"+i.to_s
			user = User.where(:email=>params[d.to_sym]).first
			if !user.nil?
				id = user.id
				group_usr = GroupUser.new
				group_usr.group_id = group.id
				group_usr.user_id = id
				group_usr.save!
			end
			i=i+1
		end
		
		redirect_to :action=> 'groups'
	end
	def groups
		@all_groups = current_user.groups
	end
	def info
		@group = Group.where(:id=>params[:id]).first
		@group_users = @group.group_users
	end
	def other
		# @groups=current_user.group_users
		# @all_groups=Group.where(:group_id => @groups.group_id)
		# select * from groups inner join group_users on
		#  group_users.group_id=groups.id where group_users.user_id =2;
		#  Group.
		@all_groups= Group.select("*").joins(:group_users).where(:user_id => current_user.id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
	def compose
	end
	def inbox
		@inbox = Message.where(:receiver_id=>current_user.id).reverse
	end
	def sent_mails
		@sent_mails = Message.find_by_sql("select m1.* from messages m1 left outer join messages m2 on (m1.ticket_id = m2.ticket_id and m1.id < m2.id) where m2.id is null;")
		#@sent_mails = Message.where(:sender_id=>current_user.id).reverse
	end
	def create_mail
		ticket_id = 0
		if !params[:ticket_id].nil? && params[:ticket_id]!=0
			ticket_id = params[:ticket_id].to_i
		else
			ticket_id = Message.maximum("ticket_id").to_i+1
		end
		to = params[:email]
		message_body = params[:message]
		sender_id = current_user.id 
		user = User.where(:email=>to).first
		if !user.nil?
			receiver_id = user.id
			chat = Message.new
			chat.sender_id = sender_id
			chat.receiver_id = receiver_id
			chat.message = message_body
			chat.ticket_id = ticket_id
			chat.save!
		else
			#here no receive id exists.so don't send mail
		end
		 redirect_to action: 'sent_mails'
	end
	def history
		@id = params[:ticket_id]
		@chat_history = Message.where(:ticket_id=>@id).reverse
		if @chat_history.first.receiver_id == current_user.id
			@rec_id = @chat_history.first.sender_id
		else
			@rec_id = @chat_history.first.receiver_id
		end
		puts "%"*50
		puts @chat_history.inspect
		puts "%"*50
		@ticket_id = @chat_history.first.ticket_id
	end
end

app/controllers/problem_controller.rb
class ProblemController < ApplicationController
	def add
	end
	def all
		@problem= Problem.all.reverse
	end
	def create_problem
		problem_title = params[:title]
		problem_statement = params[:statement]
		question = Problem.new
		question.user_id= current_user.id 
		question.name=problem_title
		question.statement=problem_statement
		question.save!
		redirect_to action: 'all'
	end
	def view
		problem_id = params[:id]
		@problem = Problem.find(problem_id)
	    @comments = Comment.where(:problem_id => problem_id).reverse
	end
		
	def user_problems
		@all_user_problems = current_user.problems.reverse
	end
	def edit
		problem_id = params[:id]
		@problem = Problem.find(problem_id)
	end

	def edit_problem
		problem_id = params[:id]
		problem_title = params[:title]
		problem_statement = params[:statement]
		question = Problem.find(problem_id)
		question.user_id= current_user.id 
		question.name=problem_title
		question.statement=problem_statement
		question.save!
		redirect_to action: 'user_problems'
	end

	def add_comment
		problem_id = params[:id]
		comment_body = params[:comment_body]
		on_comment = Comment.new
		on_comment.user_id = current_user.id
		on_comment.problem_id = problem_id
		on_comment.comment = comment_body
		on_comment.save!
		redirect_to action: 'view'
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def about
	end
	def contact
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailer_helper.rb
module MailerHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/group/groups.html.erb
<div class="container">
<table class="table table-striped">
	<thead>
		<td>Group Name</td>
		<td>Group members</td>
	</thead>
<%@all_groups.each do |group|%>
	 <tr>
		<td> 
			<a href="info/<%= group.id%>" style="text-decoration:none ; color: #333333">			
			<div style="height:100%;width:100%">
     			<%= group.name%>
     		</div>
     		</a>
     	</td>
		<td><a href="" style="text-decoration:none ; color: #333333" >			
			<div style="height:100%;width:100%">
     			<%=group.no_of_members%>
     		</div>
     		</a>
     	</td>
	</tr>
<%end%>
</table>
</div>

app/views/group/index.html.erb
<style>
.form-control{
	width: 150;
}
</style>
<br/><br/>
<div class="container">
<div class="well">
<%= form_tag group_create_path(), :method => :get, :class => "form-horizontal" do %>
  <div class="form-group">
    <label class="col-sm-2 control-label">Group Name</label>
    <div class="col-sm-6">
      <input  name="name" class="form-control" placeholder="Group Name">
    </div>
  </div>
  <div class="form-group">
    <label  class="col-sm-2 control-label">Group Members</label>
    <div class="col-sm-3">
      <input type="text" id="members" name="no_of_members" style="width:40px" value="1" readonly="readonly" class="form-control" />
        <img alt="Add_icon"  id="add" style="cursor:pointer;color:blue" height="20" src="/assets/add.png" width="20">
        <img alt="Add_icon"  id="remove" style="cursor:pointer;color:blue" height="20" src="/assets/minus2.png" width="20">
        <div id="group-members">
        <input type="text" name="user_1" class="form-control" value="<%= current_user.email%>" disabled></input>
        </div>

    </div>

  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <button type="submit" class="btn btn-primary">Add Group</button>
    </div>
  </div>
<%end%>
</div>
</div>

<script>
function add_row(i)
{
  var row="";
  row = '<input type="text" name="user_'+i+'" class="form-control" placeholder="Email"></input>';
  $('div#group-members').append(row);

}
</script>

<script>
$("img#add").on('click',function(){
    no_of_members = parseInt($('#members').val());
    $('#members').val( no_of_members + 1);
    add_row(no_of_members+1);
});
$("img#remove").on('click',function(){
    remove_member = parseInt($('#members').val());
    if(remove_member>=2){
    $('#members').val( remove_member - 1);
    $('#group-members input:last-child').remove();}
});
</script>

app/views/group/info.html.erb
<div class="container">
<div class="well">
	<div >
    	<label class="col-sm-2 control-label">Group Name</label>
    	<p><%= @group.name%></p><br/>	
  	</div>
  </div>
 </div>

<div class="container">
<div class="well">
	<div >
    	<label class="col-sm-2 control-label">Number of Memebrs</label>
    	<p><%= @group.no_of_members%></p>
  	</div>
  </div>
 </div>


  <br/>
 
<% @group_users.each do |user| %> 
 <div class="container">
<div class="well">
  <div >
      <p><%= User.where(:id=>user.user_id).first.email %></p>
    </div>
  </div>
 </div>
<% end %>

app/views/group/other.html.erb
<div class="container">
<table class="table table-striped">
	<thead>
		<td>Group Name</td>
		<td>Group members</td>
	</thead>
<%@all_groups.each do |group|%>
	 <tr>
		<td> 
			<a href="info/<%= group.id%>" style="text-decoration:none ; color: #333333">			
			<div style="height:100%;width:100%">
     			<%= group.name%>
     		</div>
     		</a>
     	</td>
		<td><a href="" style="text-decoration:none ; color: #333333" >			
			<div style="height:100%;width:100%">
     			
     		</div>
     		</a>
     	</td>
	</tr>
<%end%>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodoHub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="/assets/heading_style"/>
  <%#= stylesheet_link_tag    'heading_style', media: "all"%>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">CODOHUB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!--<li><%#= link_to "Homepage",homepage_path()%></li>-->
            <li><%= link_to "About",about_path()%></li>
            <!--<li><%#= link_to "Contact",contact_path()%></li>-->
          </ul>
          <% if !current_user.nil? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Other Groups",group_other_path()%></li>
            <li><%= link_to "My Groups",group_groups_path()%></li>
            <li><%= link_to "Create Group",group_index_path()%></li>
            <li><%= link_to "My Problems",user_all_problems_path()%></li>
            <li><%= link_to "All Problem",problem_all_path()%></li>
            <li><%= link_to "Add Problem",problem_add_path()%></li>
            <li><%= link_to "Sent",sent_mails_path()%></li>
            <li><%= link_to "Inbox",mailer_inbox_path()%></li>
            <li><%= link_to "Compose",mailer_compose_path()%></li>
            <li class="user">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user"></i>&nbsp;<%=current_user.email%><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Messages</a></li>
                <li><a href="#">Invite Friends</a></li>
                <li><a href="#">Docs</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Api</li>
                <li><a href="#">Settings</a></li>
                <li><%= link_to "Logout",destroy_user_session_path(),:method=>:delete%></li>
              </ul>
            </li>
          </ul>
          <%else%>
          <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "All Problem",problem_all_path()%></li>
            <li><%= link_to "Sign in",new_user_session_path()%></li>
            <li><%= link_to "Sign up",new_user_registration_path()%></li>
          </ul>
          <%end%>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <br/>
  <br/>
  <br/>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<script>
       // This script is making selected li from nav tab active .
       $(document).ready(function() {
       var pageTitle = window.location.pathname;
       // The above window.location.pathname will give url of current page
       pageTitle=pageTitle.toLowerCase();
       //The above two line is to filtering the pagetitle for the correct match
       $('ul.nav.navbar-nav a').each(function () {
            var str = $(this).attr('href').toLowerCase();
            if(pageTitle.match(str))
            {
              $(this).parent().addClass("active"); 
            }
         });
       });
</script>

</body>
</html>

app/views/problem/add.html.erb
<style>
.form-control{
	width: 150;
}
</style>
<br/><br/>
<div class="container">
<div class="well">
<%= form_tag create_problem_path(), :method => :get, :class => "form-horizontal" do %>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-6">
      <input  name="title" class="form-control" id="inputEmail3" placeholder="Title">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Problem Statement</label>
    <div class="col-sm-6">
      <textarea class="form-control" name="statement"  rows="15" placeholder="Describe Your Problem Here"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <button type="submit" class="btn btn-primary">Add Problem</button>
    </div>
  </div>
<%end%>
</div>
</div>

app/views/problem/all.html.erb
<div class="container">
<table class="table table-striped">
	<thead>
		<td>Problem Name</td>
		<td>Problem Statement</td>
	</thead>
<%@problem.each do |problem|%>
	 <tr>
		<td> 
			<a href="view/<%=problem.id%>" style="text-decoration:none ; color: #333333">			
			<div style="height:100%;width:100%">
     			<%=problem.name%>
     		</div>
     		</a>
     	</td>
		<td><a href="view/<%=problem.id%>" style="text-decoration:none ; color: #333333" >			
			<div style="height:100%;width:100%">
     			<%=problem.statement.at(0..30)%>
     		</div>
     		</a>
     	</td>
	</tr>
<%end%>
</table>
</div>

app/views/problem/edit.html.erb
<style>
.form-contol{
	width: auto;
}
</style>
<br/><br/>
<div class="container">
<div class="well">
<%= form_tag user_edit_problem_path(:id => @problem.id), :method => :get, :class => "form-horizontal" do %>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-6">
      <input  name="title" class="form-control" id="inputEmail3" placeholder="Title" value="<%= @problem.name%>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Problem Statement</label>
    <div class="col-sm-6">
      <textarea class="form-control" name="statement" rows="15" placeholder="Describe Your Problem Here"><%= @problem.statement%></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
  </div>
<%end%>
</div>
</div>

app/views/problem/user_problems.html.erb
<div class="container">
<table class="table table-striped">
	<thead>
		<td>Problem Name</td>
		<td>Problem Statement</td>
	</thead>
<% @all_user_problems.each do |problem|%>
	<!--  <tr>
		<td><%= link_to problem.name, problem_view_path(:id=>problem.id)%></td>
		<td><%=problem.statement%></td>
		<td><%= link_to "Edit", user_edit_path(:id=>problem.id),:class=>"btn btn-primary"%></td>
	</tr> -->
	 <tr>
		<td> 
			<a href="/problem/view/<%=problem.id%>" style="text-decoration:none ; color: #333333">			
			<div style="height:100%;width:100%">
     			<%=problem.name%>
     		</div>
     		</a>
     	</td>
		<td><a href="/problem/view/<%=problem.id%>" style="text-decoration:none ; color: #333333" >			
			<div style="height:100%;width:100%">
     			<%=problem.statement.at(0..30)%>
     		</div>
     		</a>
     	</td>
     	<td><%= link_to "Edit", user_edit_path(:id=>problem.id),:class=>"btn btn-primary"%></td>
	</tr>
<%end%>
</table>
</div>

app/views/problem/view.html.erb
<div class="container">
<div class="well">
	<div >
    	<label class="col-sm-2 control-label">Title</label>
    	<p><%= @problem.name%></p><br/>	
  	</div>
  </div>
 </div>

<div class="container">
<div class="well">
	<div >
    	<label class="col-sm-2 control-label">Statement</label>
    	<p><%= @problem.statement%></p>
  	</div>
  </div>
 </div>


  <br/>
  <br/>
<div class="container">
      <label class="col-sm-2 control-label">Comments</label>
 </div>
<% @comments.each do |comment| %> 
 <div class="container">
<div class="well">
  <div >
      <label class="col-sm-2 control-label"><%= comment.user_id %></label>
      <p><%= comment.comment %></p>
    </div>
  </div>
 </div>
<% end %>

 <% if !current_user.nil? %>
  <%= form_tag problem_add_comment_path(:id => @problem.id), :method => :get, :class => "form-horizontal" do %>
  <div class="form-group">
    <label class="col-sm-2 control-label"><%=current_user.id%></label>
    <div class="col-sm-6">
      <textarea class="form-control" name="comment_body"  rows="3" placeholder="Add Comment"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <button type="submit" class="btn btn-primary">Add Comment</button>
    </div>
  </div>
<%end%>
<%end%>

app/views/staticpages/about.html.erb
<p>
<h2>ABOUT</h2>
Originally, this document was prepared during the summers of 2014 to help the freshers of Indian Institute of Technology, Kanpur. So, we thought it might be useful to others as well.

<h2>The community</h2>
Codohub is not just a contest platform - it's a community for aspiring programmers.
We host events online and in person
We support anyone who wants to start their own Codohub Campus Chapter or host a Codohub Meetup
Our Forums, Blog, Facebook Group and Twitter stream help everyone stay updated and connected.
Over 25,000 people worldwide have joined Codohub so far, and we're always looking for more.
<h2>The Freelancers</h2>
Codohub relies on its dedicated community to help us run the site. Our expert team of freelancers bakes up new problems and moderates our forums. If you're interested in helping out, visit our Problem Setting page or contact us to become moderators.
<h2>Contact</h2>
If you have any suggestions on how we can make Codohub better, or if you have any questions, please don't hesitate to get in touch. Just use feedback@codohub.com.</p>

app/views/staticpages/contact.html.erb
<link rel="stylesheet" id="js-hr-typography" type="text/css" href="/assets/contact/file1.css" data-noprefix />
<link href="/assets/contact/file2.css" media="all" rel="stylesheet" type="text/css" />
  <link href="/assets/contact/file4.css" media="all" rel="stylesheet" type="text/css" />
  <link href="/assets/contact/file3.css" media="all" rel="stylesheet" type="text/css" />
<div class="static-section static-hero x-hero">
        <div class="container--flex">
          <h2 class="static_hero-title text-inverse balance-text">Contact Us</h2>

          <p class="static_hero-content balance-text">Have a question? Drop us a line; we are here to help.</p>

          <div id="response-container" class="hidden" style="color: #ffffff">
          </div>

          <form name="contact-us-form">
            <div class="formgroup row">
              <div class="span-xs-16 span-lg-8">
                <textarea id="contact-us-message" class="fw tall resizey" placeholder="Message"></textarea>
              </div>
              <div class="span-xs-16 span-lg-8 input-wrap">
                <input name="fullName" id="fullName" type="text" placeholder="Full Name" class="fw"/>
                <input name="email" id="email" type="email" placeholder="Email" class="fw"/>

                <div class="btn-wrap">
                  <button type='submit' class="btn btn-primary btn-large primary-dark">Send Email</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <section class="static-section text-center xcontact-email">
        <div class="container--flex">
          <h4 class="xcontact-emailink">Email: <a href="mailto:coders@codohub.com" class="btn-text color-green">coders@codohub.com</a>
          </h4>
        </div>
      </section>
       <section class="static-section xcontact-address fill-grey">
        <div class="container--flex">
          <div class="row">
            <div class="span-xs-16 span-lg-8 xcontact-address-block">
              <h3>United States <a href="tel:1-415-900-4023" class="btn-text color-green">1-415-900-402</a></h3>
              <address>
                215 Castro Street, 3rd Floor<br/>
                Mountain View<br/>
                California 94041
              </address>
            </div>
            <div class="span-xs-16 span-lg-8 xcontact-address-block">
              <h3>India <a href="tel:+91 8306689455" class="btn-text color-green">+91 8306689455</a></h3>
              <address>
                # 1002, Rushikesh Appartment<br>
                Near Dinner Bell Hotel,<br>
                Subhash Chowk, Memnagar <br>Ahmedabad<br>
              </address>
            </div>
          </div>
        </div>
      </section>
      <div class="plT plB static-footer fill-dark">
  <div class="container--flex">
    <div class="row mlT mlB">
      <div class="span-xs-16 span-lg-2ofthree x-footer-links">
        <div class="row">
          <!--<ul class="unstyled mlB span-xs-16 span-sm-8 span-md-4">
              <li><p class="color-alt-grey mmB"><strong>Interviewstreet</strong></p></li>
              <li><a href="https://www.interviewstreet.com/recruit2/howitworks/" target ="_blank">Features</a></li>
              <li><a href="https://www.interviewstreet.com/recruit2/pricing/" target ="_blank">Pricing</a></li>
              <li><a href="https://www.interviewstreet.com/recruit2/codepair" target ="_blank">Codepair</a></li>
          </ul>-->
          <ul class="unstyled mlB span-xs-16 span-sm-third">
            <li><p class="color-alt-grey mmB"><strong>Company</strong></p></li>
            <li><%=link_to "About Us",about_path()%></li>
            <li><a href="interns/2014.html">Interns</a></li>
            <li><a href="careers.html">Careers</a></li>
            <li><a href="http://blog.hackerrank.com/">Blog</a></li>
          </ul>
          <ul class="unstyled mlB span-xs-16 span-sm-third">
            <li><p class="color-alt-grey mmB"><strong>Docs</strong></p></li>
            <li><a href="scoring.html">Scoring</a></li>
            <li><a href="environment.html">Environment</a></li>
            <li><a href="faq.html">FAQ</a></li>
          </ul>
          <ul class="unstyled mlB span-xs-16 span-sm-third">
            <li><p class="color-alt-grey mmB"><strong>Other</strong></p></li>
            <li><a href="privacy.html">Privacy Policy</a></li>
            <li><a href="http://webchat.freenode.net/?channels=hackerrank" target="_blank">Freenode</a></li>
            <li><%=link_to "Contact Us",contact_path()%></li>
          </ul>
        </div>
      </div>
      <div class="span-xs-16 span-sm-16 span-lg-third x-footer-brand">
        <p>&copy; 2014 CodoHub</p>
        <p class="msT"><a href="https://www.facebook.com/hackerrank" target="_blank">Facebook</a> - <a href="https://twitter.com/hackerrank" target="_blank">Twitter</a></p>
      </div>
    </div>
  </div>
</div>